name: connect
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.25.4
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  flutter_webrtc: ^0.9.48+hotfix.1
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  permission_handler: ^11.3.0
  provider: ^6.1.1
  uuid: ^3.0.5
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: ProtestRiot
      fonts:
        - asset: assets/fonts/ProtestRiot-Regular.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/profile_picture.jpg