name: connect
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5  # Allow minor updates
  firebase_auth: ^4.17.5  # Allow minor updates
  cupertino_icons: ^1.0.2  # Allow minor updates
  curved_navigation_bar: ^1.0.3  # Allow minor updates
  firebase_core: ^2.25.4  # Allow minor updates
  firebase_storage: ^11.2.3  # Allow minor updates
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1  # Allow minor updates
  flutter_staggered_grid_view: ^0.6.2  # Allow minor updates
  flutter_svg: ^2.0.7  # Allow minor updates
  flutter_webrtc: ^0.9.48+hotfix.1  # Allow patch updates
  geolocator: ^11.0.0  # Allow minor updates
  google_maps_flutter: ^2.5.3  # Allow minor updates
  image_picker: ^1.0.7  # Allow minor updates
  intl: ^0.19.0  # Allow minor updates
  permission_handler: ^11.3.0  # Allow minor updates
  provider: ^6.1.1  # Allow minor updates
  uuid: ^3.0.5  # Allow minor updates
  video_player: ^2.8.2  # Allow minor updates

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: ProtestRiot
      fonts:
        - asset: assets/fonts/ProtestRiot-Regular.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/profile_picture.jpg


